export enum AreaEnum {
  'FORUM',
  "Chełm",
  "Aniołki",
  "Wrzeszcz",
  "Przymorze",
  "Brzeźno",
  "Letnica",
  "Oliwa",
  "Morena",
  "Orlowo",
  "Redlowo",
  "Wzgórze S.M.",
  "Karviny",
  "Maly kack",
  "Glówna",
  "Chulonia",
  "Sopot",
  "Pruszcz",
}

export enum ProductsEnum {
  "Шш ICE CREAM CAKE" = "Шш ICE CREAM CAKE",
  "Гашиш Gelato OG" = "Гашиш Gelato OG",
  "CUPCAKES 🧁 " = "CUPCAKES 🧁 ",
  "MDMA Brown" = "MDMA Brown",
  "Extasy “Cerberus”" = "Extasy “Cerberus”",
  "Мефедрон 4mmc" = "Мефедрон 4mmc",
  "Клефедрон 4cmc" = "Клефедрон 4cmc",
  "Метафедрон 3 mmc" = "Метафедрон 3 mmc",
  "Амфетамин" = "Амфетамин",
  "Кокаин" = "Кокаин",
  "LSD" = "LSD",
  "Грибы RW" = "Грибы RW",
  "Кетамин" = "Кетамин",
  "Ксанакс 2 мг" = "Ксанакс 2 мг",
  "Бунорфин 8 мг" = "Бунорфин 8 мг",
  "Оксидолор 80 mg" = "Оксидолор 80 mg",
  "Прегабалин 300 mg" = "Прегабалин 300 mg",
}